variables:
    GIT_SSL_NO_VERIFY: "true"


test:
  image: maven:3.3.9-jdk-8
  variables:
      MAVEN_OPTS: -Dmaven.repo.local=/cache/maven.repository
  script:
    - rm -rf /cache/maven.repository
    - mvn clean verify exec:java